.PHONY: clean All

All:
	@echo "----------Building project:[ first-problem - Debug ]----------"
	@cd "first-problem" && "$(MAKE)" -f  "first-problem.mk"
clean:
	@echo "----------Cleaning project:[ first-problem - Debug ]----------"
	@cd "first-problem" && "$(MAKE)" -f  "first-problem.mk" clean
