.PHONY: clean All

All:
	@echo "----------Building project:[ P-01 - Debug ]----------"
	@cd "P-01" && "$(MAKE)" -f  "P-01.mk"
clean:
	@echo "----------Cleaning project:[ P-01 - Debug ]----------"
	@cd "P-01" && "$(MAKE)" -f  "P-01.mk" clean
